{% set name = "django-url-filter" %}
{% set version = "0.3.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-url-filter-{{ version }}.tar.gz
  sha256: 12d66e4ff0150e10fd4efd1ec292a06a2cec6311ec2e4bd1fc99b2fea18e2a7b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools

  run:
    - python >={{ python_min }}
    - cached-property
    - django >=1.8
    - enum-compat
    - six
    - setuptools

test:
  imports:
    - url_filter
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/miki725/django-url-filter
  summary: Django URL Filter provides a safe way to filter data via human-friendly URLs.
  license: MIT
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - rxm7706
